---
- hosts: servers
  become: true
  tasks:
  - name: create user
    ansible.builtin.user:
      name: user1
      shell: /bin/bash
      group: users
      home: "/home/user1"

  - name: —Åreate directory
    file:
      path=/home/user1/.ssh
      state=directory
      owner=user1
      group=users

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
        src: /home/user1/.ssh/id_rsa.pub
        dest: /home/user1/.ssh/id_rsa.pub
        owner: user1
        group: users
        # mode: '0644'

  - name: add autorized key
    authorized_key:
      user: user1
      state: present
      key: "{{ lookup('file', '/home/user1/.ssh/id_rsa.pub') }}"
