---
# tasks file for nginx_php

- name: install nginx ana php packages
  ansible.builtin.apt:
    name:
      - nginx
      - php
      - php-fpm
    state: present
    update_cache: yes

- ufw:
    rule: allow
    port: 80
    proto: tcp

- name: delete default nginx vhost and symlink
  file:
        path: "{{ item }}"
        state: absent
  loop:
        - /etc/nginx/sites-available/default
        - /etc/nginx/sites-enabled/default

- name: setup nginx vhost
  template:
        src: nginx.conf
        dest: /etc/nginx/sites-available/my-site.conf

- name: create symlink nginx vhost
  file:
        src: /etc/nginx/sites-available/my-site.conf
        dest: /etc/nginx/sites-enabled/my-site.conf
        state: link
  notify: restart nginx

- name: add nginx config
  ansible.builtin.template:
    src: index.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: 0644

## change DocumentRoot

- name: create custom directory
  ansible.builtin.file:
        path: /opt/nginx/ansible
        state: directory

- name: copy files to the new location
  ansible.builtin.copy:
    src: /var/www/html/index.php
    dest: /opt/nginx/ansible
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0644

- name: add changes to config
  lineinfile:
    dest: /etc/nginx/sites-available/my-site.conf
    regexp: 'root /var/www/html; '
    line: 'root /opt/nginx/ansible;'
    state: present
  notify: restart nginx
