---
# tasks file for php

- name: install php packages
  ansible.builtin.apt:
    name:
      - php
      - php-fpm
    state: present
    update_cache: yes

- name: add changes to php config
  lineinfile:
    dest: /etc/php/7.4/fpm/pool.d/www.conf
    regexp: 'listen = /run/php/php7.4-fpm.sock'
    line: 'listen = 9000'
    state: present

- ufw:
    rule: allow
    port: 9000

- name: add php file
  ansible.builtin.template:
    src: index.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: 0644
