---
# tasks file for vsftpd

 - name: install package 
   ansible.builtin.apt:
    name: vsftpd
    state: present

 - name: copy config file
   template:
        src: vsftpd.conf.j2
        dest: "/etc/vsftpd.conf"
        owner: root
        group: root
        mode: 0644
   notify: restart vsftpd

 - name: start service
   service: name=vsftpd state=started enabled=yes
